rename "my_Image[0].jpg"	rename "my_Image[0].jpg"
rename "my_Image[10].jpg"	rename "my_Image[10].jpg"
rename "my_Image[11].jpg"	rename "my_Image[11].jpg"
rename "my_Image[12].jpg"	rename "my_Image[12].jpg"
rename "my_Image[13].jpg"	rename "my_Image[13].jpg"
rename "my_Image[14].jpg"	rename "my_Image[14].jpg"
rename "my_Image[15].jpg"	rename "my_Image[15].jpg"
rename "my_Image[1].jpg"	rename "my_Image[1].jpg"
rename "my_Image[2].jpg"	rename "my_Image[2].jpg"
rename "my_Image[3].jpg"	rename "my_Image[3].jpg"
rename "my_Image[4].jpg"	rename "my_Image[4].jpg"
rename "my_Image[5].jpg"	rename "my_Image[5].jpg"
rename "my_Image[6].jpg"	rename "my_Image[6].jpg"
rename "my_Image[7].jpg"	rename "my_Image[7].jpg"
rename "my_Image[8].jpg"	rename "my_Image[8].jpg"
rename "my_Image[9].jpg"	rename "my_Image[9].jpg"

